### Test the root endpoint
GET http://localhost:8787/

### Test the greet endpoint
GET http://localhost:8787/greet/Gemini

### Test the echo endpoint
GET http://localhost:8787/echo/hello-world

### Test the scrape endpoint
GET http://localhost:8787/scrape?url=https://example.com

### Test the Yahoo Finance stock scraping endpoint
GET http://localhost:8787/stock/AAPL

### Test Yahoo Finance 6758.T stock quote
GET http://localhost:8787/stock/6758.T

### Test multiple Yahoo Finance stock codes
GET http://localhost:8787/stock/6758.T,5016.T,998407.O

### Test Yahoo Finance ^DJI stock quote
GET http://localhost:8787/stock/^DJI

### Test Yahoo Finance USDJPY=FX stock quote
GET http://localhost:8787/stock/USDJPY=FX
